title = "Ei saa aru"
baseURL = "https://eisaaaru.ee"

languageCode = "et-ee"
defaultcontentlanguage = "et"

disableKinds = ["sitemap", "section"]
taxonomies = {}
noTimes = true
noChmod = true

[params]
  description = "Podcast inimeseks olemisest ja tehnoloogiast"
  author = "Henno ja Siim"
  email = "eisaaaru@eisaaaru.ee"
