baseURL = "https://eisaaaru.ee"
languageCode = "et-ee"
defaultcontentlanguage = "et"
title = "Ei saa aru"
disableKinds = ["sitemap"]

taxonomies = {}

[params]
  description = "Podcast tehnoloogiast ja inimeseks olemisest"
  author = "Henno ja Siim"
  email = "eisaaaru@p6drad-teel.net"
