baseURL = "https://eisaaaru.ee"
languageCode = "et-ee"
defaultcontentlanguage = "et"
title = "Ei saa aru"
disableKinds = ["sitemap", "section"]

noTimes = true
noChmod = true

taxonomies = {}

[params]
  description = "Podcast tehnoloogiast ja inimeseks olemisest"
  author = "Henno ja Siim"
  email = "eisaaaru@eisaaaru.ee"
